spring.application.name=GestionClinicasYCitas


## MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/dbsistemamedico?createDatabaseIfNotExists=true
spring.datasource.user=WilliamAlexanderOtzoyGonzalez
spring.datasource.password=admin

## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true